routes/web.php
<?php

use Illuminate\Support\Facades\Route;

//Route::redirect('/', 'login');
Route::redirect('/home', '/admin');

Route::get('/', 'WebController@index');

//Route::get('/home', 'HomeController@index')->name('home');

Auth::routes(['register' => false]);

Route::get('/admin', "HomeController@admin")->name('admin');

Route::resource('/table', "TableController");
Route::resource('/category', "CategoryController");
Route::resource('/menu', "MenuController");
Route::resource('/orderlist', "OrderController");

Route::post('/cart/add', 'CartController@add')->name('cart')->middleware('auth');

Route::get('/cart', 'CartController@index')->name('checkout')->middleware('auth');
Route::get('/cart/clear', 'CartController@clear')->name('clear')->middleware('auth');
Route::delete('/cart/destroy/{itemId}', 'CartController@destroy')->name('cart.destroy')->middleware('auth');
Route::patch('/cart/update/{itemId}', 'CartController@update')->name('cart.update')->middleware('auth');
Route::post('/order', 'CartController@order')->name('cart.order')->middleware('auth');

Route::get('/orderlist/status/{id}', "OrderController@status")->name('orderlist.status')->middleware('auth');

Route::get('/setting/{userId}', 'UserController@show')->name('user.setting');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    public function menus()
    {
        return $this->hasMany('App\Menu');
    }

    public function scopeFilterOn($query)
    {
        if (request('category_id')) {
            return $query->where('id', request('category_id'));
        }
    }

}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::orderBy('category_name')->get();
        return view('admin.category.index', [
            'categories' => $categories,
            'no' => 1,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'category_name' => 'required',
        ]);

        $category = new Category();
        $category->category_name = $request->category_name;
        $category->save();
        return redirect()->route('category.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        $category = Category::find($category->id);
        return view('admin.category.edit', [
            'category' => $category,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $request->validate([
            'category_name' => 'required',
        ]);
        $category = Category::find($category->id);
        $category->category_name = $request->category_name;
        $category->updated_at = now();
        $category->update();
        return redirect()->route('category.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->delete();
        return back();
    }
}

resources/views/admin/category/create.blade.php
@extends('admin.layout.master')

@section('title', "Dashboard")

@section('content')
<div class="clearfix" >
  <div class="float-left">
    <h1 class="cafe-title">Add New Category</h1>
  </div>
  <div class="float-right">
    <a href="{{route('category.index')}}" class="mb-2 mr-2 btn cafe-search mb-4">Back</a>
  </div>
</div>

  <div class="main-card mb-3 card">
    <div class="card-body p-5">
        <form class="" method="post" action="{{route('category.store')}}">
        @csrf
            <div class="position-relative form-group">
              <label for="name" class="">Category Name</label>
              <input name="category_name" id="name" placeholder="Enter the Category name" type="text" class="form-control @error('category_name') border-danger @enderror">
              @error('category_name')
                <p class="text-danger mt-3">{{$message}}</p>
              @enderror
            </div>

            <button class="mt-1 btn cafe-search">Add New</button>
        </form>
    </div>
</div>

@endsection

resources/views/admin/category/edit.blade.php
@extends('admin.layout.master')

@section('title', "Dashboard")

@section('content')
<div class="clearfix" >
  <div class="float-left">
    <h1 class="cafe-title">Edit Category</h1>
  </div>
  <div class="float-right">
    <a href="{{route('category.index')}}" class="mb-2 mr-2 btn cafe-search mb-4">Back</a>
  </div>
</div>

  <div class="main-card mb-3 card">
    <div class="card-body p-5">
        <form class="" method="post" action="{{route('category.update', $category->id)}}">
        @csrf
        @method('patch')
            <div class="position-relative form-group">
              <label for="name" class="">Category Name</label>
              <input name="category_name" id="name" placeholder="Enter the Category name" type="text" class="form-control @error('category_name') border-danger @enderror" value="{{$category->category_name}}">
              @error('category_name')
                <p class="text-danger mt-3">{{$message}}</p>
              @enderror
            </div>

            <button class="mt-1 btn cafe-search">Update Category</button>
        </form>
    </div>
</div>

@endsection

resources/views/admin/category/index.blade.php
@extends('admin.layout.master')

@section('title', "Dashboard")

@section('content')


<div class="clearfix" >
  <div class="float-left">
    <h1 class="cafe-title">Category List</h1>
  </div>
  <div class="float-right">
    <a href="{{route('category.create')}}" class="mb-2 mr-2 btn cafe-search mb-4">Add New category</a>
  </div>
</div>

  <div class="card ">
    <table class="mb-0 table table-striped">
      <thead>
      <tr class="cafe-category-table-header">
          <th class="pt-4 pb-4">#</th>
          <th class="pt-4 pb-4">Category Name</th>
          <th class="pt-4 pb-4">Action</th>
      </tr>
      </thead>
      <tbody>
      @foreach($categories as $category)
        <tr>
            <th scope="row">{{$no++}}</th>
            <td style="text-transform: capitalize;">{{$category->category_name}}</td>
            <td>

              <a href="{{route('category.edit', $category->id)}}" title="Edit" class="btn ">
                <i class="metismenu-icon pe-7s-note2 h5 text-success"></i>
              </a>


              <form action="{{ route('category.destroy', $category->id) }}" onsubmit="return confirm('{{ 'Are You Sure' }}');" method="POST" class="d-inline">
                @csrf
                @method('DELETE')
                <button type="submit" class="btn" title="Delete">
                  <i class="metismenu-icon pe-7s-trash h5 text-danger" ></i>
                </button>
            </form>

            </td>
        </tr>
      @endforeach
      </tbody>
    </table>

  </div>
@endsection