routes/web.php
<?php

use Illuminate\Support\Facades\Route;

//Route::redirect('/', 'login');
Route::redirect('/home', '/admin');

Route::get('/', 'WebController@index');

//Route::get('/home', 'HomeController@index')->name('home');

Auth::routes(['register' => false]);

Route::get('/admin', "HomeController@admin")->name('admin');

Route::resource('/table', "TableController");
Route::resource('/category', "CategoryController");
Route::resource('/menu', "MenuController");
Route::resource('/orderlist', "OrderController");

Route::post('/cart/add', 'CartController@add')->name('cart')->middleware('auth');

Route::get('/cart', 'CartController@index')->name('checkout')->middleware('auth');
Route::get('/cart/clear', 'CartController@clear')->name('clear')->middleware('auth');
Route::delete('/cart/destroy/{itemId}', 'CartController@destroy')->name('cart.destroy')->middleware('auth');
Route::patch('/cart/update/{itemId}', 'CartController@update')->name('cart.update')->middleware('auth');
Route::post('/order', 'CartController@order')->name('cart.order')->middleware('auth');

Route::get('/orderlist/status/{id}', "OrderController@status")->name('orderlist.status')->middleware('auth');

Route::get('/setting/{userId}', 'UserController@show')->name('user.setting');

app/Http/Controllers/TableController.php
<?php

namespace App\Http\Controllers;

use App\Table;
use Illuminate\Http\Request;

class TableController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tables = Table::orderBy('table_name')->get();
        return view('admin.table.index', [
            'tables' => $tables,
            'no' => 1,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.table.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'table_name' => ['required', 'unique:tables'],
        ]);

        $table = new Table();
        $table->table_name = $request->table_name;
        $table->save();
        return redirect()->route('table.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Table  $table
     * @return \Illuminate\Http\Response
     */
    public function show(Table $table)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Table  $table
     * @return \Illuminate\Http\Response
     */
    public function edit(Table $table)
    {
        return view('admin.table.edit', [
            'table' => $table,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Table  $table
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Table $table)
    {
        $request->validate([
            'table_name' => ['required', 'unique:tables'],
        ]);

        $table = Table::find($table->id);
        $table->table_name = $request->table_name;
        $table->updated_at = now();
        $table->save();
        return redirect()->route('table.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Table  $table
     * @return \Illuminate\Http\Response
     */
    public function destroy(Table $table)
    {
        $table->delete();
        return back();
    }
}

resources/views/admin/table/create.blade.php
@extends('admin.layout.master')

@section('title', "Dashboard")

@section('content')

<div class="clearfix" >
  <div class="float-left">
    <h1 class="cafe-title">Add New Table</h1>
  </div>
  <div class="float-right">
    <a href="{{route('table.index')}}" class="mb-2 mr-2 btn cafe-search mb-4">Back</a>
  </div>
</div>



  <div class="main-card mb-3 card">
    <div class="card-body p-5">
        <form class="" method="post" action="{{route('table.store')}}">
        @csrf
            <div class="position-relative form-group">
              <label for="name" class="">Table Name</label>
              <input name="table_name" id="name" placeholder="Enter the table name" type="text" class="form-control @error('table_name') border-danger @enderror">
              @error('table_name')
                <p class="text-danger mt-3">{{$message}}</p>
              @enderror
            </div>

            <button class="mt-1 btn cafe-search">Add New</button>
        </form>
    </div>
</div>

@endsection

resources/views/admin/table/edit.blade.php
@extends('admin.layout.master')

@section('title', "Dashboard")

@section('content')
<div class="clearfix" >
  <div class="float-left">
    <h1 class="cafe-title">Edit Table</h1>
  </div>
  <div class="float-right">
    <a href="{{route('table.index')}}" class="mb-2 mr-2 btn cafe-search mb-4">Back</a>
  </div>
</div>

  <div class="main-card mb-3 card">
    <div class="card-body p-5">
        <form class="" method="post" action="{{route('table.update', $table->id)}}">
        @csrf
        @method('patch')
            <div class="position-relative form-group">
              <label for="name" class="">Table Name</label>
              <input name="table_name" id="name" placeholder="Enter the table name" type="text" class="form-control @error('table_name') border-danger @enderror" value="{{$table->table_name}}">
              @error('table_name')
                <p class="text-danger mt-3">{{$message}}</p>
              @enderror
            </div>

            <button class="mt-1 btn cafe-search">Edit Table</button>
        </form>
    </div>
</div>

@endsection

resources/views/admin/table/index.blade.php
@extends('admin.layout.master')

@section('title', "Dashboard")

@section('content')

  <div class="clearfix" >
      <div class="float-left">
        <h1 class="cafe-title">Table List</h1>
      </div>
      <div class="float-right">
        <a href="{{route('table.create')}}" class="mb-2 mr-2 btn cafe-search mb-4">Add New Table</a>
      </div>
  </div>

  <!-- <div class="card">
  <table class="mb-0 table table-hover ">
    <thead>
    <tr>
        <th>#</th>
        <th>Table Name</th>
        <th>Action</th>
    </tr>
    </thead>
    <tbody>
    @foreach($tables as $table)
      <tr>
          <th scope="row">{{$no++}}</th>
          <td>{{$table->table_name}}</td>
          <td>

            <a href="{{route('table.edit', $table->id)}}" title="Edit"><i class="metismenu-icon pe-7s-note2 h5 text-success"></i></a>
            <span class="ml-4"></span>

            <a href="#" title="Trash" onclick="document.getElementById('destroy-table-{{ $table->id }}').submit();">
              <i class="metismenu-icon pe-7s-trash h5 text-danger"></i>
            </a>
            <form action="{{ route('table.destroy', $table->id) }}" id="destroy-table-{{ $table->id }}" method="POST">
              @csrf
              @method('DELETE')
          </form>

          </td>
      </tr>
    @endforeach
    </tbody>
  </table>
  </div> -->

  <div class="row bg-light pt-4 pb-4 pl-2 pr-2">
  @foreach($tables as $table)
  <div class="col-md-6 col-xl-4 mb-3 mt-3">
        <div class="card ">
            <!-- <div class="widget-content-wrapper text-white">
                <div class="widget-content-left">
                    <div class="widget-heading">Table No. {{$table->table_name}}</div>
                    <div class="mt-2">
                      <a href="{{route('table.edit', $table->id)}}" title="Edit" class="btn btn-light">
                        <i class="metismenu-icon pe-7s-note2 h5 text-success"></i>
                      </a>
                      <form action="{{ route('table.destroy', $table->id) }}" method="POST" onsubmit="return confirm('{{ 'Are You Sure' }}');" class="d-inline">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-light" title="Delete">
                        <i class="metismenu-icon pe-7s-trash h5 text-danger" ></i>
                        </button>
                      </form>
                    </div>
                </div>
                <div class="widget-content-right">
                    <div class="widget-numbers text-white"><span class="h1"> {{$table->table_name}}</span></div>
                </div>
            </div> -->
            <h1 class="text-center pt-4 pb-4 cafe-table-title"> <i class="fas fa-couch"></i> {{$table->table_name}}</h1>
            <div class="mt-2 clearfix">
              <span class='h6 text-secondary p-3 float-left'>Table NO. ({{$table->table_name}})</span>
              <div class="float-right">
                <a href="{{route('table.edit', $table->id)}}" title="Edit" class="btn">
                  <i class="metismenu-icon pe-7s-note2 h5 text-primary"></i>
                </a>
                <form action="{{ route('table.destroy', $table->id) }}" method="POST" onsubmit="return confirm('{{ 'Are You Sure' }}');" class="d-inline">
                  @csrf
                  @method('DELETE')
                  <button type="submit" class="btn" title="Delete">
                  <i class="metismenu-icon pe-7s-trash h5 text-danger" ></i>
                  </button>
                </form>
              </div>
            </div>
        </div>
    </div>
    @endforeach
  </div>

@endsection