routes/web.php
<?php

use Illuminate\Support\Facades\Route;

//Route::redirect('/', 'login');
Route::redirect('/home', '/admin');

Route::get('/', 'WebController@index');

//Route::get('/home', 'HomeController@index')->name('home');

Auth::routes(['register' => false]);

Route::get('/admin', "HomeController@admin")->name('admin');

Route::resource('/table', "TableController");
Route::resource('/category', "CategoryController");
Route::resource('/menu', "MenuController");
Route::resource('/orderlist', "OrderController");

Route::post('/cart/add', 'CartController@add')->name('cart')->middleware('auth');

Route::get('/cart', 'CartController@index')->name('checkout')->middleware('auth');
Route::get('/cart/clear', 'CartController@clear')->name('clear')->middleware('auth');
Route::delete('/cart/destroy/{itemId}', 'CartController@destroy')->name('cart.destroy')->middleware('auth');
Route::patch('/cart/update/{itemId}', 'CartController@update')->name('cart.update')->middleware('auth');
Route::post('/order', 'CartController@order')->name('cart.order')->middleware('auth');

Route::get('/orderlist/status/{id}', "OrderController@status")->name('orderlist.status')->middleware('auth');

Route::get('/setting/{userId}', 'UserController@show')->name('user.setting');

app/Menu.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Menu extends Model
{

    public function scopeFilterOn($query)
    {
        //dd(request('category_id'));
        if (request('category_id')) {
            return $query->where('category_id', request('category_id'));
        }
        // elseif(request('status') == 'trash'){
        //     $query->onlyTrashed();
        // }
    }

    public function category()
    {
        return $this->belongsTo('App\Category');
    }

    public function orders()
    {
        return $this->belongsToMany('App\Order', 'order_menu', 'menu_id', 'order_id');
    }

}

app/Http/Controllers/MenuController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Http\Controllers\Controller;
use App\Menu;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class MenuController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $menus = Menu::orderBy('id', 'desc')->paginate(9);
        return view('admin.menu.index', [
            'menus' => $menus,
            'no' => 1,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::orderBy('category_name')->get();
        //dd($categories);
        return view('admin.menu.create', [
            'categories' => $categories,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'menu_name' => 'required',
            'price' => 'required',
            'category_id' => 'required',
        ]);

        $menu = new Menu();
        $menu->menu_name = $request->menu_name;
        $menu->price = $request->price;
        if ($request->image) {
            $path = $request->file('image')->store('public/image');
            $menu->image = $path;
        } else {
            $menu->image = "public/image/food.png";
        }
        $menu->category_id = $request->category_id;
        $menu->save();

        return redirect()->route('menu.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Menu  $menu
     * @return \Illuminate\Http\Response
     */
    public function show(Menu $menu)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Menu  $menu
     * @return \Illuminate\Http\Response
     */
    public function edit(Menu $menu)
    {
        $categories = Category::orderBy('category_name')->get();
        return view('admin.menu.edit', [
            'menu' => $menu,
            'categories' => $categories,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Menu  $menu
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Menu $menu)
    {
        $request->validate([
            'menu_name' => 'required',
            'price' => 'required',
            'category_id' => 'required',
        ]);

        $menu->menu_name = $request->menu_name;
        $menu->price = $request->price;
        if ($request->image) {
            if ($menu->image != "public/image/food.png") {
                Storage::delete($menu->image);
            }
            $path = $request->file('image')->store('public/image');
            $menu->image = $path;
        }
        $menu->category_id = $request->category_id;
        $menu->update();

        return redirect()->route('menu.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Menu  $menu
     * @return \Illuminate\Http\Response
     */
    public function destroy(Menu $menu)
    {
        if ($menu->image != "public/image/food.png") {
            Storage::delete($menu->image);
        }

        $menu->delete();
        return back();

    }
}

resources/views/admin/menu/create.blade.php
@extends('admin.layout.master')

@section('title', "Dashboard")

@section('content')
<div class="clearfix" >
  <div class="float-left">
    <h1 class="cafe-title">Add New Menu</h1>
  </div>
  <div class="float-right">
    <a href="{{route('menu.index')}}" class="mb-2 mr-2 btn cafe-search mb-4">Back</a>
  </div>
</div>

  <div class="main-card mb-3 card">
    <div class="card-body p-5">
        <form class="" method="post" action="{{route('menu.store')}}" enctype='multipart/form-data'>
        @csrf
            <div class="position-relative form-group">
              <label for="name" class="">Menu Name</label>
              <input name="menu_name" id="name" placeholder="Enter the menu name" type="text" class="form-control @error('menu_name') border-danger @enderror">
              @error('menu_name')
                <p class="text-danger mt-3">{{$message}}</p>
              @enderror
            </div>

            <div class="position-relative form-group">
              <label for="price" class="">Price</label>
              <input name="price" id="price" placeholder="Enter the price" type="number" class="form-control @error('price') border-danger @enderror">
              @error('price')
                <p class="text-danger mt-3">{{$message}}</p>
              @enderror
            </div>

            <div class="position-relative form-group">
              <label for="image" class="">Menu Image</label>
              <input name="image" id="image" type="file" class="form-control-file">
            </div>

            <div class="position-relative form-group">
              <select class="mb-2 form-control" name="category_id">
              @foreach($categories as $category)
                  <option value="{{$category->id}}">{{$category->category_name}}</option>
              @endforeach
              </select>
            </div>

            <button class="mt-1 btn cafe-search">Add New</button>
        </form>
    </div>
</div>

@endsection

resources/views/admin/menu/edit.blade.php
@extends('admin.layout.master')

@section('title', "Dashboard")

@section('content')
<div class="clearfix" >
  <div class="float-left">
    <h1 class="cafe-title">Add New Menu</h1>
  </div>
  <div class="float-right">
    <a href="{{route('menu.index')}}" class="mb-2 mr-2 btn cafe-search mb-4">Back</a>
  </div>
</div>
  <div class="main-card mb-3 card">
    <div class="card-body p-5">
        <form class="" method="post" action="{{route('menu.update', $menu->id)}}" enctype='multipart/form-data'>
        @csrf
        @method('patch')
            <div class="position-relative form-group">
              <label for="name" class="">Menu Name</label>
              <input name="menu_name" id="name" placeholder="Enter the menu name" type="text" class="form-control @error('menu_name') border-danger @enderror" value="{{$menu->menu_name}}">
              @error('menu_name')
                <p class="text-danger mt-3">{{$message}}</p>
              @enderror
            </div>

            <div class="position-relative form-group">
              <label for="price" class="">Price</label>
              <input name="price" id="price" placeholder="Enter the price" type="number" class="form-control @error('price') border-danger @enderror" value="{{$menu->price}}">
              @error('price')
                <p class="text-danger mt-3">{{$message}}</p>
              @enderror
            </div>

            <div class="position-relative form-group">
            <img src="{{ url('storage/'.str_replace('public/', '', $menu->image)) }}" class="card-img-top" alt="..." style="width: 200px; height: 150px" >
            </div>

            <div class="position-relative form-group">
              <label for="image" class="">Menu Image</label>
              <input name="image" id="image" type="file" class="form-control-file">
            </div>

            <div class="position-relative form-group">
              <select class="mb-2 form-control" name="category_id">
              @foreach($categories as $category)
                  <option value="{{$category->id}}"
                  @if($menu->category_id == $category->id)
                    selected
                  @endif
                  >{{$category->category_name}}</option>
              @endforeach
              </select>
            </div>

            <button class="mt-1 btn cafe-search">Update Menu</button>
        </form>
    </div>
</div>

@endsection

resources/views/admin/menu/index.blade.php
@extends('admin.layout.master')

@section('title', "Dashboard")

@section('content')
<div class="clearfix" >
  <div class="float-left">
    <h1 class="cafe-title">Menu List</h1>
  </div>
  <div class="float-right">
    <a href="{{route('menu.create')}}" class="mb-2 mr-2 btn cafe-search mb-4">Add New Menu</a>
  </div>
</div>

<div class="mt-5 mb-4">
      {{$menus->links()}}
</div>

  <div class="card">
    <table class="mb-0 table table-striped ">
      <thead>
      <tr class="cafe-category-table-header">
          <th class="pt-4 pb-4">#</th>
          <th class="pt-4 pb-4">Menu Name</th>
          <th class="pt-4 pb-4">Price</th>
          <th class="pt-4 pb-4">Image</th>
          <th class="pt-4 pb-4">Category</th>
          <th class="pt-4 pb-4">Action</th>
      </tr>
      </thead>
      <tbody>
      @foreach($menus as $menu)
        <tr>
            <th scope="row">{{$no++}}</th>
            <td>{{$menu->menu_name}}</td>
            <td>{{$menu->price}}</td>
            <td>
              <img src="{{ url('storage/'.str_replace('public/', '', $menu->image)) }}" class="card-img-top" alt="..." style="width: 200px; height: 150px" >
            </td>
            <td>{{$menu->category->category_name}}</td>
            <td>

                <a href="{{route('menu.edit', $menu->id)}}" title="Edit" class="btn">
                  <i class="metismenu-icon pe-7s-note2 h5 text-success"></i>
                </a>


                <form action="{{ route('menu.destroy', $menu->id) }}" onsubmit="return confirm('{{ 'Are You Sure' }}');" method="POST" class="d-inline">
                  @csrf
                  @method('DELETE')
                  <button type="submit" class="btn" title="Delete">
                    <i class="metismenu-icon pe-7s-trash h5 text-danger" ></i>
                  </button>
              </form>

              </td>
        </tr>
      @endforeach
      </tbody>
    </table>
</div>
<div class="mt-5 mb-5">
      {{$menus->links()}}
</div>


@endsection