routes/web.php
<?php

use Illuminate\Support\Facades\Route;

//Route::redirect('/', 'login');
Route::redirect('/home', '/admin');

Route::get('/', 'WebController@index');

//Route::get('/home', 'HomeController@index')->name('home');

Auth::routes(['register' => false]);

Route::get('/admin', "HomeController@admin")->name('admin');

Route::resource('/table', "TableController");
Route::resource('/category', "CategoryController");
Route::resource('/menu', "MenuController");
Route::resource('/orderlist', "OrderController");

Route::post('/cart/add', 'CartController@add')->name('cart')->middleware('auth');

Route::get('/cart', 'CartController@index')->name('checkout')->middleware('auth');
Route::get('/cart/clear', 'CartController@clear')->name('clear')->middleware('auth');
Route::delete('/cart/destroy/{itemId}', 'CartController@destroy')->name('cart.destroy')->middleware('auth');
Route::patch('/cart/update/{itemId}', 'CartController@update')->name('cart.update')->middleware('auth');
Route::post('/order', 'CartController@order')->name('cart.order')->middleware('auth');

Route::get('/orderlist/status/{id}', "OrderController@status")->name('orderlist.status')->middleware('auth');

Route::get('/setting/{userId}', 'UserController@show')->name('user.setting');

resources/views/admin/layout/header.blade.php
<div class="app-header header-shadow">
    <div class="app-header__logo">
        <!-- <div class="logo-src"></div> -->
        <div class="cafe-title "> <div class="h4">Romance Cafe</div></div>
        <div class="header__pane ml-auto">
            <div>
                <button type="button" class="hamburger close-sidebar-btn hamburger--elastic" data-class="closed-sidebar">
                    <span class="hamburger-box">
                        <span class="hamburger-inner"></span>
                    </span>
                </button>
            </div>
        </div>
    </div>
    <div class="app-header__mobile-menu">
        <div>
            <button type="button" class="hamburger hamburger--elastic mobile-toggle-nav">
                <span class="hamburger-box">
                    <span class="hamburger-inner"></span>
                </span>
            </button>
        </div>
    </div>
    <div class="app-header__menu">
        <span>
            <button type="button" class="btn-icon btn-icon-only btn btn-primary btn-sm mobile-toggle-header-nav">
                <span class="btn-icon-wrapper">
                    <i class="fa fa-ellipsis-v fa-w-6"></i>
                </span>
            </button>
        </span>
    </div>    <div class="app-header__content">
        <div class="app-header-left">
        </div>
        <div class="app-header-right">
            <div class="header-btn-lg pr-0">
                <div class="widget-content p-0">
                    <div class="widget-content-wrapper">
                        @yield('cart')
                        <div class="widget-content-left">

                            <div class="btn-group">
                                <a data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="p-0 btn">
                                    <!-- <img width="42" class="rounded-circle" src="assets/images/avatars/1.jpg" alt=""> -->
                                    <i class="fa fa-user"></i>
                                    {{ Auth::user()->name }}
                                    <i class="fa fa-angle-down ml-2 opacity-8"></i>
                                </a>
                                <div tabindex="-1" role="menu" aria-hidden="true" class="dropdown-menu dropdown-menu-right">

                                        <li class="dropdown nav-item">
                                            <a href="{{route('user.setting', Auth::user()->id )}}" class="nav-link">
                                                <i class="nav-link-icon fa fa-cog"></i>
                                                Settings
                                            </a>
                                        </li>

                                        <li class="dropdown nav-item">
                                            <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                            document.getElementById('logout-form').submit();" class="nav-link">
                                                <i class="fas fa-sign-out-alt"></i> &nbsp
                                                {{ __('Logout') }}
                                            </a>
                                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            @csrf
                                        </form>
                                        </li>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
          </div>
    </div>
</div>

resources/views/admin/layout/master.blade.php
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Content-Language" content="en">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>@yield('title')</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, shrink-to-fit=no" />
    <meta name="description" content="This is an example dashboard created using build-in elements and components.">
    <meta name="msapplication-tap-highlight" content="no">
    <link href="{{asset('main.css')}}" rel="stylesheet">
    <link href="{{asset('css/app.css')}}" rel="stylesheet">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Alice&display=swap" rel="stylesheet">
</head>
<body>
    <div class="app-container app-theme-white body-tabs-shadow fixed-sidebar fixed-header">
        @include('admin.layout.header')
        <!-- @include('admin.layout.setting') -->
        <div class="app-main">
            @include('admin.layout.sidebar')
            <div class="app-main__outer">
                <div class="app-main__inner">
                    @yield('content')
                </div>
                <!-- <div class="app-wrapper-footer">
                    <div class="app-footer">
                        <div class="app-footer__inner">
                            <div class="app-footer-left">
                                <ul class="nav">
                                    <li class="nav-item">
                                        <a href="javascript:void(0);" class="nav-link">
                                            Footer Link 1
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="javascript:void(0);" class="nav-link">
                                            Footer Link 2
                                        </a>
                                    </li>
                                </ul>
                            </div>
                            <div class="app-footer-right">
                                <ul class="nav">
                                    <li class="nav-item">
                                        <a href="javascript:void(0);" class="nav-link">
                                            Footer Link 3
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="javascript:void(0);" class="nav-link">
                                            <div class="badge badge-success mr-1 ml-0">
                                            home                           <small>NEW</small>
                                            </div>
                                            Footer Link 4
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>     -->
            </div>
        <script src="http://maps.google.com/maps/api/js?sensor=true"></script>
        </div>
    </div>
<script type="text/javascript" src="{{asset('/assets/scripts/main.js')}}"></script></body>
</html>

resources/views/admin/layout/sidebar.blade.php
<div class="app-sidebar sidebar-shadow bg-happy-green sidebar-text-light">
    <div class="app-header__logo">
        <div class="logo-src"></div>
        <div class="header__pane ml-auto">
            <div>
                <button type="button" class="hamburger close-sidebar-btn hamburger--elastic" data-class="closed-sidebar">
                    <span class="hamburger-box">
                        <span class="hamburger-inner"></span>
                    </span>
                </button>
            </div>
        </div>
    </div>
    <div class="app-header__mobile-menu">
        <div>
            <button type="button" class="hamburger hamburger--elastic mobile-toggle-nav">
                <span class="hamburger-box">
                    <span class="hamburger-inner"></span>
                </span>
            </button>
        </div>
    </div>
    <div class="app-header__menu">
        <span>
            <button type="button" class="btn-icon btn-icon-only btn btn-primary btn-sm mobile-toggle-header-nav">
                <span class="btn-icon-wrapper">
                    <i class="fa fa-ellipsis-v fa-w-6"></i>
                </span>
            </button>
        </span>
    </div>
    <div class="scrollbar-sidebar">
        <div class="app-sidebar__inner">
            <ul class="vertical-nav-menu">
                <li class="app-sidebar__heading">Dashboards</li>
                <li>
                    <a href="{{route('admin')}}" class="{{Request::path() === 'admin' ? 'mm-active' : '' }}">
                        <i class="metismenu-icon pe-7s-airplay"></i>
                        Dashboard
                    </a>
                </li>
                @if(Auth::user()->role == 1)
                <li class="app-sidebar__heading">Tables</li>
                <li>
                    <a href="{{route('table.index')}}" class="{{Request::path() === 'table' ? 'mm-active' : '' }}">
                        <i class="metismenu-icon pe-7s-network"></i>
                        Tables List
                    </a>
                </li>
                <li>
                    <a href="{{route('table.create')}}" class="{{Request::path() === 'table/create' ? 'mm-active' : '' }}">
                        <i class="metismenu-icon pe-7s-pen"></i>
                        Add new Table
                    </a>
                </li>
                <li class="app-sidebar__heading">Categories</li>
                <li>
                    <a href="{{route('category.index')}}" class="{{Request::path() === 'category' ? 'mm-active' : '' }}">
                        <i class="metismenu-icon pe-7s-file"></i>
                        Cateogries List
                    </a>
                </li>
                <li>
                    <a href="{{route('category.create')}}" class="{{Request::path() === 'category/create' ? 'mm-active' : '' }}">
                        <i class="metismenu-icon pe-7s-pen"></i>
                        Add new Category
                    </a>
                </li>
                <li class="app-sidebar__heading">Menus</li>
                <li>
                    <a href="{{route('menu.index')}}" class="{{Request::path() === 'menu' ? 'mm-active' : '' }}">
                        <i class="metismenu-icon pe-7s-note2"></i>
                        Menus List
                    </a>
                </li>
                <li>
                    <a href="{{route('menu.create')}}" class="{{Request::path() === 'menu/create' ? 'mm-active' : '' }}">
                        <i class="metismenu-icon pe-7s-note"></i>
                        Add new Menu
                    </a>
                </li>

                <li class="app-sidebar__heading">Order</li>
                <li>
                    <a href="{{route('orderlist.index')}}" class="{{Request::path() === 'orderlist' ? 'mm-active' : '' }}">
                        <i class="metismenu-icon pe-7s-note2"></i>
                        Order List
                    </a>
                </li>
                @elseif(Auth::user()->role == 3 || Auth::user()->role == 2)
                <li class="app-sidebar__heading">Order</li>
                <li>
                    <a href="{{route('orderlist.index')}}" class="{{Request::path() === 'orderlist' ? 'mm-active' : '' }}">
                        <i class="metismenu-icon pe-7s-note2"></i>
                        Order List
                    </a>
                </li>
                @endif
            </ul>
        </div>
    </div>
</div>